#!/usr/bin/env sh

# Replace environment variables in nginx config in the ${} shell format
# with their values. Only ENV variables in the list will be replaced.
envsubst '${PORT},${APP_HOST}' < ./nginx.conf > ./nginx.conf

nginx -c ./nginx.conf
